### PR TITLE
IDA 7.4 get_highlighted_identifier() compatibility

### PR DESCRIPTION
**Pull request by laomaiweng**
IDA 7.4 removed `get_highlighted_identifier()`: see https://www.hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml

### CODE REVIEW

**Comment by repnz** [comment]
Thanks for submitting a fix! :) really appreciate it
Did you test this change?
Also, I wonder if it works with previous versions of IDA as well.. Maybe we should remove this if statement

**Comment by laomaiweng** [comment]
I did test the change with IDA 7.5, but not earlier versions. According to the hex-rays.com page I linked above:

> Note that the new APIs have been baked in IDAPython since IDA 7.0, meaning that by porting existing IDAPython code according to this guide, you will not just support IDA 7.4: the ported code will also work in IDA 7.3, 7.2, 7.1 and 7.0.

So yeah I guess removing the `if` would totally be an option, if you don't mind targeting only IDA 7.0+.

By the way, thanks for sharing this awesome plugin! :)

**Comment by laomaiweng** [comment]
Or, I just found out that Sark has a `sark.get_highlighted_identifier()` function that does exactly what the Hex-Rays link suggests (so shouldn't be compatible with IDA 6.x).

**Comment by repnz** [comment]
I don't think I'll support IDA 6.x because of the API changes they did.. So yeah you can just change it to sark.get_highlighted_identifier()

**Comment by repnz** [comment]
Thanks for the information. This commit should fix the issue: 29de22189b35ce75241c80999573422d5903802a

**Pull request closed without merging**
